trafficcontroller:
  image: zlchen/trafficcontroller:latest
  hostname: trafficcontroller
  ports:
    - "8081"
    - "9911"
  restart: always

nozzle:
  image: zlchen/nozzle:latest
  hostname: nozzle
  ports:
    - "9912"
  environment:
    - API_ENDPOINT=http://trafficcontroller:9911
    - API_USER=admin
    - API_PASSWORD=admin
    - SPLUNK_TOKEN=00000000-0000-0000-0000-000000000000
    - SPLUNK_HOST=https://heclb1:8088
    - SPLUNK_INDEX=main
    - SKIP_SSL_VALIDATION_CF=true
    - SKIP_SSL_VALIDATION_SPLUNK=true
  restart: always
